### PR TITLE
Add Mahindra cars data

### PR DESCRIPTION
**Pull request by aalaap**
Adds the following cars from [Mahindra](https://www.carwale.com/mahindra-cars/) (India) to the list:

- Alturas G4
- Bolero
- KUV100
- KUV100 NXT
- Marazzo
- Scorpio
- Scorpio Getaway
- TUV300
- TUV300 PLUS
- Thar
- Verito
- Verito Vibe CS
- XUV500
- e20 NXT
- e2o PLUS
- eKUV100
- XUV300

Note that the e2o PLUS and e20 NXT aren't spelling mistakes - they are actually e2o and e20 for some particular reason.

This is a fun package! I love it!

### CODE REVIEW

**Comment by aalaap** [comment]
@pelmered Travis CI is reporting that this is failing on PHP 7.2, but passing fine on older versions. I'm not sure what's wrong here. Can you take a look?

**Comment by pelmered** [comment]
Thanks a lot for the PR @aalaap!

It is not an error in your code. 
I think you need to add return types on the tests in the new PHP Unit (version 8). 

For example: `public function setUp()` should now be `public function setUp() : void`

**Comment by aalaap** [comment]
I see. Let me try adding the return type. This should work with all versions of PHP 7.

**Comment by pelmered** [comment]
Ok, great. I will merge and tag a new version as soon as you have pushed this and the tests are passing.

**Comment by aalaap** [comment]
Now `setUp(): void` does not work with PHP 7.0 - it only works on 7.1 onwards. How do you want to proceed?

**Comment by aalaap** [comment]
Since this is a breaking change in PHPUnit 8, I would expect the `composer.json` line `"phpunit/phpunit": "^5.7"` to automatically avoid 8.x, but perhaps PHPUnit hasn't declared it breaking. For the time being, I'm going to try and manually avoid the new version.

**Comment by aalaap** [comment]
Even after setting the range to `>=5.7 <8`, it doesn't work. The semver range is [correct](https://semver.mwl.be/#?package=phpunit%2Fphpunit&version=%3E%3D5.7%20%20%3C8&minimum-stability=stable).

:-(

**Comment by aalaap** [comment]
I give up.

**Comment by pelmered** [comment]
I managed to solve it [here](https://github.com/pelmered/fake-car/pull/7) by using the PHPUnit version from the vendor dir. That way composer takes care of all the dependency checks and because PHP Unit 8 does not support PHP 7.0 it will install an older version. 

I would like to add the car data from the original PR. 

Maybe PHP 7.0 support should be dropped as it is now EOL: http://php.net/supported-versions.php

**Comment by aalaap** [comment]
Even I considered dropping PHP 7 support, but it felt like a little too big a decision in order to just use a newer PHPUnit version. Using an older version that does the job is a better idea.

Thanks!

**Pull request merged**
